export const strings = {
    title: 'Choose Your Skip Size',
    subtitle: 'Select the skip size that best suits your needs',
    heavyWasteError: 'Not Suitable for Heavy Waste',
    privatePropertyWarning: 'Private Property Only',
    imageURL: 'https://images.unsplash.com/photo-1590496793929-36417d3117de?q=80&w=800',
    apiURL: 'https://app.wewantwaste.co.uk/api/skips/by-location?postcode=NR32&area=Lowestoft',
    backButton: 'Back',
    continueButton: 'Continue',
    selected: 'Selected',
    selectThisSkip: 'Select This Skip',
    plusVAT: '+ VAT',
    currency: '£',
    perWeek: 'per week',
    dayHirePeriod: 'day hire period',
    yardSkip: 'Yard Skip',
    yardSkipPopup: 'Yard Skip - ',
    postcodeLabel: 'Postcode',
    wasteTypeLabel: 'Waste Type',
    selectSkipLabel: 'Select Skip',
    permitCheckLabel: 'Permit Check',
    chooseDateLabel: 'Choose Date',
    paymentLabel: 'Payment',
}